"""Build a minimal public/ tree for hosting (no maintainer scripts).

The calculator only needs HTML, layouts, JSON data, and Assets. Python
generators, README, Retired_scripts, etc. must stay in the git repo and
should not be uploaded to the web server.

Usage:
    python3 build_public.py
    python3 build_public.py --out public
    python3 build_public.py --clean   # wipe out dir first

Then upload the contents of public/ (or the folder itself, depending on
your host) — e.g. rsync, SCP, or your CMS static upload.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Paths relative to repo root that the live calculator needs at runtime.
PUBLIC_ITEMS = [
    "index.html",
    "curriculum_manifest.json",
    "course_aliases.json",
    "Assets",
    "Programs",
    "Programs_old",
    "Course_requisites",
    "Transition_courses",
]

# Explicitly NOT copied (for maintainers reading this file):
#   *.py, README.md, Retired_scripts/, Programs_misc/, course_correction.html,
#   programs_config.json, __pycache__/, .git/, .DS_Store


def copy_item(src: Path, dest: Path) -> None:
    if src.is_dir():
        shutil.copytree(
            src,
            dest,
            ignore=shutil.ignore_patterns(
                ".DS_Store",
                "__pycache__",
                "*.pyc",
                ".git",
            ),
            dirs_exist_ok=False,
        )
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)


def build(out_dir: Path, clean: bool) -> None:
    if clean and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    missing = []
    for name in PUBLIC_ITEMS:
        src = ROOT / name
        if not src.exists():
            missing.append(name)
            continue
        dest = out_dir / name
        if dest.exists():
            if dest.is_dir():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        copy_item(src, dest)
        print(f"  + {name}")

    if missing:
        raise SystemExit(f"Missing required paths: {', '.join(missing)}")

    # Small marker so hosts/people know this folder is generated
    (out_dir / ".public_build").write_text(
        "Generated by build_public.py — do not add maintainer scripts here.\n",
        encoding="utf-8",
    )
    print(f"\nPublic tree ready: {out_dir}")
    print("Upload only this folder's contents to the web host.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Copy runtime-only files into a public/ folder for hosting",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "public",
        help="Output directory (default: ./public)",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the output directory before copying",
    )
    args = parser.parse_args()
    out = args.out if args.out.is_absolute() else (ROOT / args.out)
    print(f"Building public site → {out}")
    build(out, clean=args.clean)


if __name__ == "__main__":
    main()
