import os, re, json

#regex pattern to filter out files with name type <Program-name>-<YYYY>.json, accepts both upper/lower case letters for program name
pattern = re.compile(r"^([A-Za-z]+)-([0-9]{4})\.json$")

relative_path = "./Programs"

entries = {}
program_course_hashmap = {}
for folder in os.listdir(relative_path):
    program_course_hashmap[folder] = []
    for course in os.listdir(os.path.join(relative_path, folder)):
        if pattern.match(course):
            program_course_hashmap[folder].append(os.path.join(relative_path,folder, course))
   

# break down basename of the files from path into <prog>:<year>

for program in program_course_hashmap:
    for prog_year in sorted(program_course_hashmap[program]):

        #extracting the year of the program
        filename = os.path.basename(prog_year)
        match = pattern.match(filename)
        if match:
            year = match.group(2)  # Group 2 captures the ([0-9]{4}) year
        else:
            continue  # Safeguard fallback

        key = f"{program}:{year}"
        try:
            with open(prog_year, 'r', encoding='utf-8') as f:
                data = json.load(f)
            entries[key] = data
        except Exception as e:
            print("Skipping", prog_year, 'due to error: ', e)

out_lines = []
out_lines.append('// This file is auto-generated by bundler_v2.py')
out_lines.append('const embeddedCurricula = (function(){')
out_lines.append('  const m = {};')
for key, data in entries.items():
    # dump JSON compact but readable
    json_text = json.dumps(data, indent=2)
    # Escape closing script tags just in case
    json_text = json_text.replace('</', r'<\/')
    out_lines.append(f'  m[{json.dumps(key)}] = {json_text};')

out_lines.append('  return m;')
out_lines.append('})();')

with open('curricula.bundle_v2.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(out_lines))

print('Wrote curricula.bundle_v2.js with', len(entries), 'entries')
