#!/usr/bin/env python3
"""
Generates `curricula.bundle.js` by reading all `*-YYYY.json` files in the
current directory and embedding them into a single JS file as the global
variable `embeddedCurricula`.

Usage:
  cd /Users/camdenhampe/curricula
  python3 generate_bundle.py

After this runs you can open `StudyPlanner - v0.7.html` directly (file://) and
it will use the embedded curricula.
"""
import os, re, json

pattern = re.compile(r"^([A-Za-z]+)-([0-9]{4})\.json$")

files = [f for f in os.listdir('.') if pattern.match(f)]
entries = {}
for fn in sorted(files):
    m = pattern.match(fn)
    prog, year = m.group(1), m.group(2)
    key = f"{prog}:{year}"
    try:
        with open(fn, 'r', encoding='utf-8') as f:
            data = json.load(f)
        entries[key] = data
    except Exception as e:
        print('Skipping', fn, 'due to error:', e)

out_lines = []
out_lines.append('// This file is auto-generated by generate_bundle.py')
out_lines.append('const embeddedCurricula = (function(){')
out_lines.append('  const m = {};')
for key, data in entries.items():
    # dump JSON compact but readable
    json_text = json.dumps(data, indent=2)
    # Escape closing script tags just in case
    json_text = json_text.replace('</', '<\/')
    out_lines.append(f'  m[{json.dumps(key)}] = {json_text};')

out_lines.append('  return m;')
out_lines.append('})();')

with open('curricula.bundle.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(out_lines))

print('Wrote curricula.bundle.js with', len(entries), 'entries')
